name: Piloto Automatico Radar

on:
  schedule:
    - cron: '0 9 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    # --- AÑADIMOS ESTO PARA DAR PERMISOS DE ESCRITURA ---
    permissions:
      contents: write
    # ---------------------------------------------------
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
    - name: 📥 Descargando código del repositorio
      uses: actions/checkout@v4

    - name: 🐍 Configurando Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: 📦 Instalando dependencias
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: 🌐 Instalando navegadores de Playwright
      run: npx playwright install chromium --with-deps

    - name: 🚀 Ejecutando Radar de Novedades
      run: python main.py

    - name: 💾 Guardando cambios en la Base de Datos
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -f radar_data.db
        git commit -m "Radar: Actualización automática de productos" || echo "No hay cambios para subir"
        git push